# Generated by Django 4.0.5 on 2023-12-19 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_shearer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='raw wool', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('qr_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=50)),
                ('softness', models.CharField(max_length=50)),
                ('quality_certificate_link', models.URLField(blank=True, null=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collector')),
                ('producers', models.ManyToManyField(to='api.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collector')),
            ],
        ),
        migrations.CreateModel(
            name='ShearingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shearer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shearer')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedWoolBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='processed wool', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('qr_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('production_date', models.DateField(auto_now_add=True)),
                ('current_location', models.CharField(default='In Factory', max_length=50)),
                ('cleanliness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('texture', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
            ],
        ),
    ]
