# Generated by Django 4.2.5 on 2023-12-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_processor_phone_producer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=50, unique=True)),
                ('production_date', models.DateField()),
                ('current_location', models.CharField(default='In Farm', max_length=50)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=50)),
                ('softness', models.CharField(max_length=50)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producer')),
            ],
        ),
    ]
