# Generated by Django 4.0.5 on 2023-12-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_batch_store_shearingrequest_processedwoolbatch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessedWoolBatch',
            new_name='ProcessedBatch',
        ),
    ]
