# Generated by Django 4.2.5 on 2023-12-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='type',
            field=models.CharField(default='raw wool', max_length=100),
        ),
    ]
