# Generated by Django 4.2.5 on 2023-12-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_batch_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='district',
            new_name='city',
        ),
        migrations.AddField(
            model_name='producer',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
