# Generated by Django 4.0.5 on 2023-12-20 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spinning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarn_type', models.CharField(max_length=50)),
                ('yarn_weight', models.CharField(max_length=50)),
                ('twist_level', models.CharField(max_length=50)),
                ('yarn_ply', models.PositiveIntegerField()),
                ('yardage', models.PositiveIntegerField()),
                ('spinning_date', models.DateField(auto_now_add=True)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('process_id', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processedbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('location', models.CharField(default='In Farm', max_length=200)),
                ('ref', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('processedstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processedstore')),
            ],
        ),
        migrations.CreateModel(
            name='Dyeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('color_fastness', models.CharField(max_length=50)),
                ('texture', models.CharField(max_length=50)),
                ('dye_type', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiber_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=50)),
                ('impurities', models.DecimalField(decimal_places=2, max_digits=5)),
                ('texture', models.CharField(max_length=50)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
