# Generated by Django 4.0.5 on 2023-12-20 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_spinning_processing_processedorder_dyeing_carding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processor')),
            ],
        ),
        migrations.RemoveField(
            model_name='processedbatch',
            name='type',
        ),
        migrations.AlterField(
            model_name='carding',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processor'),
        ),
        migrations.AlterField(
            model_name='dyeing',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processor'),
        ),
        migrations.AlterField(
            model_name='spinning',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processor'),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('location', models.CharField(default='In Farm', max_length=200)),
                ('ref', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('processedstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processedstore')),
            ],
        ),
    ]
