# Generated by Django 4.2.5 on 2023-12-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_district_processor_city_processor_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processor',
            old_name='city',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='producer',
            old_name='city',
            new_name='district',
        ),
    ]
