# Generated by Django 4.0.5 on 2023-12-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(default='In Farm', max_length=200),
        ),
    ]
