# Generated by Django 4.0.5 on 2023-12-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='production_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
