# Generated by Django 4.0.5 on 2023-12-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_batch_production_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='service_prices',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='available_services',
            new_name='services',
        ),
    ]
