# Generated by Django 4.0.5 on 2023-12-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_service_prices_serviceprovider_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_provider',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
