# Generated by Django 4.0.5 on 2023-12-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_servicerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='quantity',
        ),
    ]
