# Generated by Django 4.0.5 on 2023-12-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_servicerequest_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='processed_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
