# Generated by Django 4.0.5 on 2023-12-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_servicerequest_processed_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to='api.batch'),
        ),
    ]
