# Generated by Django 4.0.5 on 2023-12-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_batch_producer_alter_store_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producer'),
        ),
        migrations.AlterField(
            model_name='store',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producer'),
        ),
    ]
