from django.urls import path
from .views import ProducerView, LoginView, RegisterView, IsLoginView, LogoutView, ProcessorView, CollectorView, ShearerView, ShearingRequestView, MyRequestView, RequestView, BatchView, MyBatchView, StoreView, MyStoreView, OrderView, MyOrderView, ProcessedBatchView, MyProcessedBatchView, ProcessedStoreView, MyProcessedStoreView, MarketView, QRCodeView

urlpatterns = [
    path('register', RegisterView.as_view(), name='regiser'),
    path('login', LoginView.as_view(), name='login'),
    path('islogin', IsLoginView.as_view(), name='islogin'),
    path('logout', LogoutView.as_view(), name='logout'),
    # path('profile', ProducerProfileView.as_view(), name='producer_profile'),
    path('producers', ProducerView.as_view(), name='producer_list'),
    path('producer/<int:pk>', ProducerView.as_view(), name='producer_detail'),
    path('collectors', CollectorView.as_view(), name='collector_list'),
    path('collector/<int:pk>', CollectorView.as_view(), name='collector_detail'),
    path('shearers', ShearerView.as_view(), name='shearer_list'),
    path('shearer/<int:pk>', ShearerView.as_view(), name='shearer_detail'),
    path('shearing_requests', ShearingRequestView.as_view(), name='shearing_request_list'),
    path('shearing_request/<int:pk>', ShearingRequestView.as_view(), name='shearing_request_detail'),
    path('myrequest', MyRequestView.as_view(), name='my_request_list'),
    path('shearer/request', RequestView.as_view(), name='request_list'),
    path('processors', ProcessorView.as_view(), name='processor_list'),
    path('processor/<int:pk>', ProcessorView.as_view(), name='processor_detail'),
    path('collector/batches', BatchView.as_view(), name='batch_list'),
    path('collector/batch/<int:pk>', BatchView.as_view(), name='batch_detail'),
    path('collector/mybatch', MyBatchView.as_view(), name='mybatch'),
    path('collector/stores', StoreView.as_view(), name='store_list'),
    path('collector/mystore', MyStoreView.as_view(), name='my_store_list'),
    path('collector/store/<int:pk>', StoreView.as_view(), name='store_detail'),
    path('collector/orders', OrderView.as_view(), name='order_list'),
    path('processor/batches', ProcessedBatchView.as_view(), name='processed_batch_list'),
    path('processor/batch/<int:pk>', ProcessedBatchView.as_view(), name='processed_batch_detail'),
    path('processor/mybatch', MyProcessedBatchView.as_view(), name='mybatch'),
    path('processor/stores', ProcessedStoreView.as_view(), name='processed_store_list'),
    path('processor/mystore', MyProcessedStoreView.as_view(), name='my_store_list'),
    path('processor/store/<int:pk>', ProcessedStoreView.as_view(), name='store_detail'),
    path('market', MarketView.as_view(), name='market_list'),
    path('product/<int:pk>', MarketView.as_view(), name='Product_details'),
    path('processor/myorders', MyOrderView.as_view(), name='my_order_list'),
    # path('solditems', SoldItemView.as_view(), name='sold_items_list'),
    # path('order/<int:pk>', OrderView.as_view(), name='order_detail'),
    path('qr_code', QRCodeView.as_view(), name='qr_code'),
    path('qrcode/<int:pk>', QRCodeView.as_view(), name='qrcode'),
]
