from django.urls import path
from .views import ProducerView, LoginView, RegisterView, IsLoginView, LogoutView, ProcessorView, CollectorView, ShearerView
# , ProducerProfileView, QRCodeView, ServiceView, MyServiceRequestView, ServiceRequestView, MyRequestView, BatchView, BatchSearchView, StoreView, MarketView, MyStoreView, OrderView, SoldItemView, MyOrderView

urlpatterns = [
    path('register', RegisterView.as_view(), name='regiser'),
    path('login', LoginView.as_view(), name='login'),
    path('islogin', IsLoginView.as_view(), name='islogin'),
    path('logout', LogoutView.as_view(), name='logout'),
    # path('profile', ProducerProfileView.as_view(), name='producer_profile'),
    path('producers', ProducerView.as_view(), name='producer_list'),
    path('producer/<int:pk>', ProducerView.as_view(), name='producer_detail'),
    path('collectors', CollectorView.as_view(), name='collector_list'),
    path('collector/<int:pk>', CollectorView.as_view(), name='collector_detail'),
    path('shearers', ShearerView.as_view(), name='shearer_list'),
    path('shearer/<int:pk>', ShearerView.as_view(), name='shearer_detail'),
    # path('service/requests', MyServiceRequestView.as_view(), name='my_service_request_list'),
    # path('service_requests', ServiceRequestView.as_view(), name='service_request_list'),
    # path('service_request/<int:pk>', ServiceRequestView.as_view(), name='service_request_detail'),
    path('processors', ProcessorView.as_view(), name='processor_list'),
    path('processor/<int:pk>', ProcessorView.as_view(), name='processor_detail'),
    # path('myrequest', MyRequestView.as_view(), name='my_request_list'),
    # path('services', ServiceView.as_view(), name='service_list'),
    # path('service/<int:pk>', ServiceView.as_view(), name='service_detail'),
    # path('batches', BatchView.as_view(), name='batch_list'),
    # path('batch/<int:pk>', BatchView.as_view(), name='batch_detail'),
    # path('batch/search', BatchSearchView.as_view(), name='batch_search'),
    # path('stores', StoreView.as_view(), name='store_list'),
    # path('market', MarketView.as_view(), name='market_list'),
    # path('product/<int:pk>', MarketView.as_view(), name='Product_details'),
    # path('mystore', MyStoreView.as_view(), name='my_store_list'),
    # path('store/<int:pk>', StoreView.as_view(), name='store_detail'),
    # path('orders', OrderView.as_view(), name='order_list'),
    # path('myorders', MyOrderView.as_view(), name='my_order_list'),
    # path('solditems', SoldItemView.as_view(), name='sold_items_list'),
    # path('order/<int:pk>', OrderView.as_view(), name='order_detail'),
    # path('qr_code', QRCodeView.as_view(), name='qr_code'),
    # path('qrcode/<int:pk>', QRCodeView.as_view(), name='qrcode'),
]
